
name: Download and deploy

on:
  repository_dispatch:
    types: [update_resume]
  
jobs:
  download_copy_commit_push_ping:
    name: Downloading the pdf and commiting it to the repo
    runs-on: ubuntu-latest
    steps:
     
      - uses: actions/checkout@v2
        name: Checking out the repo
      
      - name: Fetch Github Release Asset
        uses: dsaltares/fetch-gh-release-asset@1.0.0
        with:
          repo: "rahul-sundaresan/latex-resume"
          file: "resume.pdf"
          target: "static/resume.pdf"
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Commit change
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "Change resume" -a
          
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      
    



